import {
  createHmac,
  randomBytes,
  scryptSync,
  timingSafeEqual,
} from 'node:crypto';
import type { APIContext, AstroCookies } from 'astro';

export const SESSION_COOKIE = 'chf_admin';
const SESSION_HOURS = 12;

function env(name: string): string | undefined {
  return import.meta.env[name] || process.env[name];
}

/* ------------------------------------------------------------------ *
 * Password hashing
 * ------------------------------------------------------------------ */

/** Format: scrypt$<saltHex>$<keyHex>. Generated by scripts/hash-password.mjs. */
export function hashPassword(password: string, salt = randomBytes(16)): string {
  const key = scryptSync(password, salt, 64);
  return `scrypt$${salt.toString('hex')}$${key.toString('hex')}`;
}

export function verifyPassword(password: string, stored: string): boolean {
  const [scheme, saltHex, keyHex] = stored.split('$');
  if (scheme !== 'scrypt' || !saltHex || !keyHex) return false;

  const expected = Buffer.from(keyHex, 'hex');
  const actual = scryptSync(password, Buffer.from(saltHex, 'hex'), expected.length);
  return actual.length === expected.length && timingSafeEqual(actual, expected);
}

/* ------------------------------------------------------------------ *
 * Sessions — an HMAC-signed expiry carried in an HttpOnly cookie.
 * Stateless, so there is no session store to keep in sync.
 * ------------------------------------------------------------------ */

function sign(payload: string, secret: string): string {
  return createHmac('sha256', secret).update(payload).digest('hex');
}

export function createSessionToken(secret: string): string {
  const expires = Date.now() + SESSION_HOURS * 60 * 60 * 1000;
  return `${expires}.${sign(`admin|${expires}`, secret)}`;
}

export function isValidSessionToken(
  token: string | undefined,
  secret: string,
): boolean {
  if (!token) return false;
  const [expiresRaw, signature] = token.split('.');
  const expires = Number(expiresRaw);
  if (!expiresRaw || !signature || !Number.isFinite(expires)) return false;
  if (Date.now() > expires) return false;

  const expected = Buffer.from(sign(`admin|${expires}`, secret), 'hex');
  const actual = Buffer.from(signature, 'hex');
  return actual.length === expected.length && timingSafeEqual(actual, expected);
}

/* ------------------------------------------------------------------ *
 * Config + guards
 * ------------------------------------------------------------------ */

export interface AuthConfig {
  passwordHash: string;
  sessionSecret: string;
}

/**
 * Returns null when the admin has not been configured yet. Every entry point
 * treats that as "locked", never as "open".
 */
export function getAuthConfig(): AuthConfig | null {
  const passwordHash = env('ADMIN_PASSWORD_HASH');
  const sessionSecret = env('ADMIN_SESSION_SECRET');
  if (!passwordHash || !sessionSecret) return null;
  return { passwordHash, sessionSecret };
}

export function isLoggedIn(cookies: AstroCookies): boolean {
  const config = getAuthConfig();
  if (!config) return false;
  return isValidSessionToken(
    cookies.get(SESSION_COOKIE)?.value,
    config.sessionSecret,
  );
}

export function setSessionCookie(
  cookies: AstroCookies,
  token: string,
  secure: boolean,
) {
  cookies.set(SESSION_COOKIE, token, {
    httpOnly: true,
    secure,
    sameSite: 'lax',
    path: '/',
    maxAge: SESSION_HOURS * 60 * 60,
  });
}

export function clearSessionCookie(cookies: AstroCookies) {
  cookies.delete(SESSION_COOKIE, { path: '/' });
}

/** Guard for admin *pages*: returns a redirect Response when not signed in. */
export function guardPage(context: APIContext): Response | null {
  if (isLoggedIn(context.cookies)) return null;
  const next = encodeURIComponent(context.url.pathname);
  return context.redirect(`/admin/login?next=${next}`, 302);
}

/** Guard for admin *API* routes: returns a 401 JSON body when not signed in. */
export function guardApi(cookies: AstroCookies): Response | null {
  if (isLoggedIn(cookies)) return null;
  return new Response(JSON.stringify({ error: 'Not signed in.' }), {
    status: 401,
    headers: { 'Content-Type': 'application/json' },
  });
}
